# Generated by Django 4.2.15 on 2024-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p'),
        ),
    ]
