# Generated by Django 4.2.15 on 2024-08-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_video_file_1080p_video_video_file_360p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_360p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file_720p',
        ),
    ]
