# Generated by Django 4.2.15 on 2024-08-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_remove_video_video_file_1080p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_bg',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbs'),
        ),
    ]
